runtime: python37
entrypoint: gunicorn -b :$PORT -k gevent 'vimhelp.webapp:create_app()'

default_expiration: "1h"

inbound_services:
- warmup

handlers:
- url: /(?:.*\.html)?
  script: auto
  secure: always
- url: /sitemap\.txt
  script: auto
  secure: always
- url: /(?:enqueue_)?update
  script: auto
  secure: always
- url: /_ah/warmup
  script: auto
  secure: always
- url: /(.+)
  static_files: static/\1
  upload: static/(.*)
  secure: always
