runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"
builtins:
- remote_api: on
libraries:
- name: grpcio
  version: 1.0.0

handlers:
- url: /(?:.*\.html)?
  script: main.app
- url: /sitemap\.txt
  script: main.app
- url: /(?:enqueue_)?update
  script: main.app
  login: admin
- url: /(.+)
  static_files: static/\1
  upload: static/(.*)
