runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"
builtins:
- remote_api: on
skip_files:
- ^(.*/)?\..*$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^README\.md$
- ^LICENSE$
- ^scripts/.*$

handlers:
- url: /(?:(?:.*?\.txt|tags)\.html)?
  script: vimhelp.app
- url: /(?:enqueue_)?update
  script: update.app
  login: admin
- url: /sitemap\.txt
  script: sitemap.app
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
