application: vimhelp-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /update
  script: update.py
  login: admin
- url: /testgetfaq
  script: testgetfaq.py
  login: admin
- url: /dumpenv
  script: dumpenv.py
  login: admin
- url: /(?:(?:.*?\.txt|tags)\.html)?
  script: vimhelp.py
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)

