application: vimhelp-hrd
version: 1
runtime: python27
api_version: 1
threadsafe: true
default_expiration: "1h"

handlers:
- url: /(?:(?:.*?\.txt|tags)\.html)?
  script: vimhelp.app
- url: /memcache_add
  script: vimhelp.app
  login: admin
- url: /update
  script: update.app
  login: admin
- url: /enqueue_update
  script: update.app
  login: admin
- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
